### ISSUE TITLE
Add analysis flow pic to analysis section

### ISSUE THREAD

**Issue by Byte7** [akshah1997/Heart-Disease-Analysis-and-Prediction-Front-End#3]
Add the analysis flow pic to analysis section and add line stating model accuracy to (79.6+-1.4)% in analysis section

**Comment by akshah1997** [comment]
Done adding the flow pic to analysis section on push **cf93a2bff407c119fafc20cdcc9474589a7e71ec**

**Comment by akshah1997** [comment]
Done adding the accuracy statement in Analysis section on push **cd3b3c01a4f9182c6db7aec65c574a5c0591aa92**

**Comment by akshah1997** [comment]
Closing this issue
