### ISSUE TITLE
Change accuracy to 87.3 +- 1.4 %

### ISSUE THREAD

**Issue by Byte7** [akshah1997/Heart-Disease-Analysis-and-Prediction-Front-End#4]
https://github.com/akshah1997/Heart-Disease-Analysis-and-Prediction-Front-End/blob/7ac77ba97e8a238c675fdb7b28eb76b974bc6277/index.html#L447

**Comment by Byte7** [comment]
reworked some parameters to enhance accuracy

**Comment by akshah1997** [comment]
Changed the accuracy's value to 87.3%.
Changes visible from - https://github.com/akshah1997/Heart-Disease-Analysis-and-Prediction-Front-End/commit/294872d1e3079228ae1cd69319f7c6928bd1277d
